<script lang="ts">
  import { Clipboard, ClipboardList, Download, X } from 'lucide-svelte';
  import type { FilamentInfo } from './engineClient';
  import { tr } from './i18n';

  interface Props {
    filaments: FilamentInfo[];
    painted: boolean;
    insertSwapPauses: boolean;
    onTogglePauses?: (value: boolean) => void;
  }

  let { filaments, painted, insertSwapPauses, onTogglePauses }: Props = $props();
  let showChecklist = $state(false);
  let checklistStatus = $state('');

  type DesktopBridge = {
    api?: {
      save_text_file?: (
        suggestedName: string,
        content: string,
      ) => Promise<{ ok: boolean; path?: string; error?: string; cancelled?: boolean; revealed?: boolean }>;
    };
  };

  const overflowCount = $derived(Math.max(0, filaments.length - 4));
  const physicalRows = $derived(filaments.map((filament) => ({
    ...filament,
    toolhead: (filament.index % 4) + 1,
    needsSharing: filament.index >= 4,
  })));

  function label(filament: FilamentInfo): string {
    return filament.settings_id || filament.filament_type || `${$tr('Filament')} ${filament.index + 1}`;
  }

  async function waitForDesktopBridge(): Promise<DesktopBridge | undefined> {
    const current = (window as unknown as { pywebview?: DesktopBridge }).pywebview;
    if (current?.api?.save_text_file) return current;

    return new Promise((resolve) => {
      const timer = window.setTimeout(() => {
        window.removeEventListener('pywebviewready', onReady);
        resolve((window as unknown as { pywebview?: DesktopBridge }).pywebview);
      }, 900);

      function onReady() {
        window.clearTimeout(timer);
        resolve((window as unknown as { pywebview?: DesktopBridge }).pywebview);
      }

      window.addEventListener('pywebviewready', onReady, { once: true });
    });
  }

  function checklistText(): string {
    const lines = [
      'MkWorld2Snap filament checklist',
      '',
      `Filaments: ${filaments.length}`,
      `Painted geometry: ${painted ? 'yes' : 'no'}`,
      `Shared physical toolheads: ${overflowCount > 0 ? 'yes' : 'no'}`,
      '',
      ...physicalRows.map((row) => `Slot ${row.index + 1} -> T${row.toolhead}: ${label(row)} ${row.colour ?? ''}`),
      '',
      painted
        ? 'Painted geometry is resolved during slicing in Snapmaker Orca.'
        : insertSwapPauses
          ? 'Swap pause notes are enabled for this build.'
          : 'Swap pause notes are disabled for this build.',
    ];
    return lines.join('\n');
  }

  async function saveChecklist() {
    const content = checklistText();
    checklistStatus = '';
    const bridge = await waitForDesktopBridge();
    if (bridge?.api?.save_text_file) {
      const result = await bridge.api.save_text_file('filament-checklist.txt', content);
      if (result.ok) {
        checklistStatus = result.path ? $tr('Saved to {path}', { path: result.path }) : $tr('Saved');
        return;
      }
      if (result.cancelled) return;
      if (result.error) checklistStatus = result.error;
    }

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'filament-checklist.txt';
    a.target = '_blank';
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    checklistStatus = $tr('Save started');
  }

  async function copyChecklist() {
    checklistStatus = '';
    try {
      await navigator.clipboard.writeText(checklistText());
      checklistStatus = $tr('Copied');
    } catch (err) {
      checklistStatus = err instanceof Error ? err.message : $tr('Copy failed');
    }
  }
</script>

<section class="filament-studio card card-padded" aria-label={$tr('Filament Studio')}>
  <div class="studio-head">
    <div>
      <span class="eyebrow">{$tr('Filament Studio')}</span>
      <h3>{$tr('Spool routing preview')}</h3>
    </div>
    <button class="ghost mini-action" type="button" onclick={() => (showChecklist = true)}>
      <ClipboardList size={15} strokeWidth={2.4} aria-hidden="true" />
      {$tr('Checklist')}
    </button>
  </div>

  <div class="studio-summary">
    <span><strong>{filaments.length}</strong> {$tr('spools')}</span>
    <span class:warn={overflowCount > 0}><strong>{overflowCount}</strong> {$tr('shared heads')}</span>
    <span class:warn={painted}><strong>{painted ? $tr('yes') : $tr('no')}</strong> {$tr('painted')}</span>
  </div>

  {#if overflowCount > 0}
    <div class="swap-advice">
      <ClipboardList size={16} strokeWidth={2.4} aria-hidden="true" />
      <span>
        {painted
          ? $tr('Painted colour changes are generated by Snapmaker Orca during slicing.')
          : $tr('More than four source spools share U1 toolheads. Enable swap stops if this project contains layer-based colour changes.')}
      </span>
    </div>
  {/if}

  {#if !painted && overflowCount > 0}
    <label class="pause-toggle">
      <input
        type="checkbox"
        checked={insertSwapPauses}
        onchange={(event) => onTogglePauses?.(event.currentTarget.checked)}
      />
      <span>{$tr('Add spool-swap stops for this build')}</span>
    </label>
  {/if}

  <div class="spool-map">
    {#each physicalRows as row}
      <div class="spool-row" class:shared={row.needsSharing}>
        <span class="colour" style="background:{row.colour ?? '#888'}"></span>
        <div>
          <strong>{label(row)}</strong>
          <span>{$tr('Source slot')} {row.index + 1} -> T{row.toolhead}</span>
        </div>
      </div>
    {/each}
  </div>
</section>

{#if showChecklist}
  <div class="checklist-backdrop" role="dialog" aria-modal="true" aria-labelledby="checklist-title" tabindex="-1" onkeydown={(event) => { if (event.key === 'Escape') showChecklist = false; }}>
    <div class="checklist-modal">
      <div class="checklist-head">
        <div>
          <span class="eyebrow">{$tr('Filament Studio')}</span>
          <h2 id="checklist-title">{$tr('Filament checklist')}</h2>
        </div>
        <button class="ghost close-button" type="button" onclick={() => (showChecklist = false)} aria-label={$tr('Close')}>
          <X size={18} strokeWidth={2.4} aria-hidden="true" />
        </button>
      </div>

      <pre class="checklist-body">{checklistText()}</pre>

      {#if checklistStatus}
        <div class="checklist-status">{checklistStatus}</div>
      {/if}

      <div class="checklist-actions">
        <button class="ghost" type="button" onclick={copyChecklist}>
          <Clipboard size={15} strokeWidth={2.4} aria-hidden="true" />
          {$tr('Copy')}
        </button>
        <button class="ghost" type="button" onclick={saveChecklist}>
          <Download size={15} strokeWidth={2.4} aria-hidden="true" />
          {$tr('Save .txt')}
        </button>
        <button class="primary" type="button" onclick={() => (showChecklist = false)}>
          {$tr('Close')}
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .filament-studio {
    display: flex;
    flex-direction: column;
    gap: 12px;
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--mint) 18%, transparent), transparent 48%),
      var(--bg-elev);
  }

  .studio-head,
  .studio-summary,
  .swap-advice,
  .pause-toggle,
  .spool-row {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .studio-head {
    justify-content: space-between;
  }

  .eyebrow {
    display: block;
    color: var(--text-muted);
    font-size: 10px;
    font-weight: 950;
    letter-spacing: .07em;
    text-transform: uppercase;
  }

  h3 {
    margin: 2px 0 0;
    color: var(--text);
    font-size: 17px;
    line-height: 1;
    font-weight: 950;
  }

  .mini-action {
    min-height: 32px;
    padding: 6px 10px;
    font-size: 12px;
  }

  .studio-summary {
    flex-wrap: wrap;
  }

  .studio-summary span {
    padding: 5px 8px;
    border: 1px solid var(--border);
    border-radius: 999px;
    background: var(--bg-elev);
    color: var(--text-muted);
    font-size: 12px;
  }

  .studio-summary strong {
    color: var(--text);
    font-weight: 950;
  }

  .studio-summary .warn {
    border-color: color-mix(in srgb, var(--warn) 42%, var(--border));
    color: var(--warn);
  }

  .swap-advice {
    align-items: flex-start;
    padding: 9px 10px;
    border-radius: 12px;
    border: 1px solid color-mix(in srgb, var(--warn) 32%, var(--border));
    background: color-mix(in srgb, var(--warn) 9%, var(--bg-elev));
    color: var(--warn);
    font-size: 12px;
    line-height: 1.35;
  }

  .pause-toggle {
    padding: 8px 10px;
    border-radius: 12px;
    background: color-mix(in srgb, var(--bg-raised) 72%, transparent);
    color: var(--text);
    font-size: 12px;
    font-weight: 850;
  }

  .pause-toggle input {
    width: 16px;
    height: 16px;
    accent-color: var(--accent);
  }

  .spool-map {
    display: grid;
    gap: 6px;
    max-height: 220px;
    overflow: auto;
  }

  .spool-row {
    min-width: 0;
    padding: 8px;
    border-radius: 12px;
    border: 1px solid var(--border);
    background: color-mix(in srgb, var(--bg-elev) 80%, transparent);
  }

  .spool-row.shared {
    border-color: color-mix(in srgb, var(--accent) 42%, var(--border));
  }

  .colour {
    width: 22px;
    height: 22px;
    flex: 0 0 auto;
    border-radius: 7px;
    border: 1px solid color-mix(in srgb, var(--ink) 25%, transparent);
  }

  .spool-row div {
    min-width: 0;
    display: grid;
    gap: 2px;
  }

  .spool-row strong,
  .spool-row span {
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .spool-row strong {
    color: var(--text);
    font-size: 12px;
    font-weight: 950;
  }

  .spool-row span {
    color: var(--text-muted);
    font-size: 11px;
  }

  .checklist-backdrop {
    position: fixed;
    inset: 0;
    z-index: 1500;
    display: grid;
    place-items: center;
    padding: 24px;
    background: rgba(17, 24, 32, 0.56);
    backdrop-filter: blur(12px);
  }

  .checklist-modal {
    width: min(720px, 100%);
    max-height: min(760px, 88vh);
    display: flex;
    flex-direction: column;
    gap: 14px;
    padding: 20px;
    border-radius: 22px;
    border: 2px solid var(--border-strong);
    background: var(--bg-elev);
    box-shadow: 0 28px 70px color-mix(in srgb, var(--ink) 34%, transparent);
  }

  .checklist-head,
  .checklist-actions {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
  }

  .checklist-head h2 {
    margin: 2px 0 0;
    color: var(--text);
    font-size: 24px;
    line-height: 1;
    font-weight: 950;
  }

  .close-button {
    width: 36px;
    height: 36px;
    padding: 0;
    flex: 0 0 auto;
  }

  .checklist-body {
    min-height: 260px;
    max-height: 52vh;
    overflow: auto;
    margin: 0;
    padding: 14px;
    border-radius: 14px;
    border: 1px solid var(--border);
    background: var(--bg-raised);
    color: var(--text);
    font-family: var(--font-mono);
    font-size: 12.5px;
    line-height: 1.55;
    white-space: pre-wrap;
  }

  .checklist-status {
    padding: 8px 10px;
    border-radius: 10px;
    background: color-mix(in srgb, var(--mint) 14%, var(--bg-elev));
    color: var(--text-muted);
    font-size: 12px;
    font-weight: 850;
  }

  .checklist-actions {
    justify-content: flex-end;
    flex-wrap: wrap;
  }

  .checklist-actions button {
    min-height: 36px;
  }
</style>
